from BaseClasses import Region

from ..base_classes import D3DLevel


class E1L5(D3DLevel):
    name = "The Abyss"
    levelnum = 4
    volumenum = 0
    keys = ["Blue"]
    location_defs = [
        {"name": "Battlelord Medkit", "id": 4, "type": "sprite"},
        {"name": "Battlelord Atomic Health 1", "id": 11, "type": "sprite"},
        {"name": "Battlelord Atomic Health 2", "id": 12, "type": "sprite"},
        {"name": "Waterfall Chaingun", "id": 24, "type": "sprite"},
        {"name": "MP Start Chaingun", "id": 78, "type": "sprite", "mp": True},
        {"name": "Battlelord Jetpack", "id": 79, "type": "sprite"},
        {"name": "Battlelord Armor", "id": 80, "type": "sprite"},
        {"name": "Cracked Wall End Atomic Health", "id": 112, "type": "sprite"},
        {"name": "Fire Pit Pipe Bombs", "id": 131, "type": "sprite"},
        {"name": "Top of Spaceship Atomic Health", "id": 216, "type": "sprite"},
        {"name": "Spaceship Shaft RPG", "id": 221, "type": "sprite"},
        {"name": "Spaceship Shaft Chaingun", "id": 222, "type": "sprite"},
        {"name": "Fire Pit Night Vision Goggles", "id": 262, "type": "sprite"},
        {"name": "Canyon Chaingun", "id": 291, "type": "sprite"},
        {"name": "MP Secret Fire Pit Armor", "id": 294, "type": "sprite", "mp": True},
        {"name": "Pipebombs near Blue Gate", "id": 311, "type": "sprite"},
        {"name": "Start Shotgun", "id": 316, "type": "sprite"},
        {"name": "Earthquake Atomic Health 1", "id": 373, "type": "sprite"},
        {"name": "Earthquake Atomic Health 2", "id": 374, "type": "sprite"},
        {"name": "Blue Key Card", "id": 375, "type": "sprite"},
        {"name": "Cracked Wall Middle Atomic Health", "id": 410, "type": "sprite"},
        {"name": "Fire Pit RPG", "id": 439, "type": "sprite"},
        {"name": "Dancing Shaman Atomic Health 1", "id": 466, "type": "sprite"},
        {"name": "Dancing Shaman Atomic Health 2", "id": 472, "type": "sprite"},
        {"name": "Dancing Shaman Atomic Health 3", "id": 473, "type": "sprite"},
        {"name": "Red Waterfall Pipe Bombs", "id": 524, "type": "sprite"},
        {"name": "Start Protective Boots", "id": 604, "type": "sprite"},
        {"name": "Bottom of Ruins Protective Boots", "id": 682, "type": "sprite"},
        {"name": "Fire Place Medkit", "id": 689, "type": "sprite"},
        {"name": "Toxic River Protective Boots", "id": 698, "type": "sprite"},
        {"name": "Start RPG", "id": 718, "type": "sprite"},
        {"name": "Secret Fire Pit Night Vision Goggles", "id": 726, "type": "sprite"},
        {"name": "Secret Fire Pit Medkit", "id": 727, "type": "sprite"},
        {"name": "Toxic River Holo Duke", "id": 733, "type": "sprite"},
        {"name": "Toxic River Medkit", "id": 734, "type": "sprite"},
        {"name": "Ruins Staircase Shotgun", "id": 737, "type": "sprite"},
        {"name": "Fire Pit Steroids", "id": 738, "type": "sprite"},
        {"name": "Cracked Wall Bottom Atomic Health", "id": 740, "type": "sprite"},
        {"name": "Cracked Wall Protective Boots", "id": 741, "type": "sprite"},
        {"name": "Cracked Wall Medkit", "id": 742, "type": "sprite"},
        {"name": "Spaceship Entrance Armor", "id": 744, "type": "sprite"},
        {"name": "Earthquake Night Vision Goggles", "id": 817, "type": "sprite"},
        {"name": "Red Waterfall Cave Protective Boots", "id": 868, "type": "sprite"},
        {"name": "MP Shrinker Room Steroids", "id": 876, "type": "sprite", "mp": True},
        {
            "name": "MP Cracked Wall Bottom Pipebombs",
            "id": 879,
            "type": "sprite",
            "mp": True,
        },
        {"name": "Canyon Pillars RPG", "id": 884, "type": "sprite"},
        {"name": "MP Fire Pit Jetpack", "id": 1032, "type": "sprite", "mp": True},
        {"name": "MP Fire Place RPG", "id": 1039, "type": "sprite", "mp": True},
        {
            "name": "MP Ruins Staircase Atomic Health",
            "id": 1041,
            "type": "sprite",
            "mp": True,
        },
        {"name": "MP Ruins Staircase Armor", "id": 1042, "type": "sprite", "mp": True},
        {
            "name": "MP Bottom of Ruins Shotgun",
            "id": 1044,
            "type": "sprite",
            "mp": True,
        },
        {"name": "Fire Pit Atomic Health", "id": 1046, "type": "sprite"},
        {"name": "Secret Fire Pit Atomic Health 1", "id": 1047, "type": "sprite"},
        {"name": "Secret Fire Pit Atomic Health 2", "id": 1048, "type": "sprite"},
        {"name": "Red Waterfall Passage", "id": 7, "type": "sector"},
        {"name": "Dancing Shaman", "id": 21, "type": "sector"},
        {"name": "Top of Spaceship", "id": 257, "type": "sector"},
        {"name": "Fire Pit Hidden Wall", "id": 354, "type": "sector"},
        {"name": "Fire Pit Teleporter", "id": 440, "type": "sector"},
        {"name": "Secret Fire Pit Ledge", "id": 441, "type": "sector"},
        {"name": "Exit", "id": 0, "type": "exit"},
    ]
