from BaseClasses import Region

from ..base_classes import D3DLevel


class E2L8(D3DLevel):
    name = "Dark Side"
    levelnum = 7
    volumenum = 1
    keys = ["Red"]
    location_defs = [
        {"id": 42, "name": "42 Pipebombs", "type": "sprite"},
        {"id": 156, "name": "156 Atomic Health", "type": "sprite"},
        {"id": 157, "name": "157 Atomic Health", "type": "sprite"},
        {"id": 203, "name": "203 Shrinker", "type": "sprite"},
        {"id": 206, "name": "206 Pipebombs", "type": "sprite"},
        {"id": 207, "name": "207 Pipebombs", "type": "sprite"},
        {"id": 211, "name": "211 RPG", "type": "sprite"},
        {"id": 212, "name": "212 Devastator", "type": "sprite"},
        {"id": 226, "name": "226 Armor", "type": "sprite"},
        {"id": 242, "name": "242 Pipebombs", "type": "sprite"},
        {"id": 247, "name": "247 Armor", "type": "sprite"},
        {"id": 251, "name": "251 Shotgun", "type": "sprite"},
        {"id": 257, "name": "257 Atomic Health", "type": "sprite"},
        {"id": 261, "name": "261 Medkit", "type": "sprite"},
        {"id": 265, "name": "265 Chaingun", "type": "sprite"},
        {"id": 266, "name": "266 RPG", "type": "sprite"},
        {"id": 269, "name": "269 Devastator", "type": "sprite"},
        {"id": 342, "name": "342 Atomic Health", "type": "sprite"},
        {"id": 343, "name": "343 Atomic Health", "type": "sprite"},
        {"id": 347, "name": "347 Armor", "type": "sprite"},
        {"id": 348, "name": "348 Atomic Health", "type": "sprite"},
        {"id": 359, "name": "359 Pipebombs", "type": "sprite"},
        {"id": 361, "name": "361 Tripmine", "type": "sprite"},
        {"id": 363, "name": "363 Pipebombs", "type": "sprite"},
        {"id": 364, "name": "364 Medkit", "type": "sprite"},
        {"id": 372, "name": "372 Shotgun", "type": "sprite"},
        {"id": 374, "name": "374 Atomic Health", "type": "sprite"},
        {"id": 375, "name": "375 Chaingun", "type": "sprite"},
        {"id": 406, "mp": True, "name": "MP 406 Chaingun", "type": "sprite"},
        {"id": 407, "name": "407 Shrinker", "type": "sprite"},
        {"id": 520, "name": "520 Blue Key Card", "type": "sprite"},
        {"id": 790, "name": "790 Freezethrower", "type": "sprite"},
        {"id": 797, "name": "797 Armor", "type": "sprite"},
        {"id": 801, "name": "801 Devastator", "type": "sprite"},
        {"id": 836, "mp": True, "name": "MP 836 RPG", "type": "sprite"},
        {"id": 837, "name": "837 Pipebombs", "type": "sprite"},
        {"id": 843, "name": "843 Yellow Key Card", "type": "sprite"},
        {"id": 932, "name": "932 Armor", "type": "sprite"},
        {"id": 952, "name": "952 Night Vision Goggles", "type": "sprite"},
        {"id": 953, "name": "953 Steroids", "type": "sprite"},
        {"id": 954, "name": "954 Holo Duke", "type": "sprite"},
        {"id": 955, "name": "955 Protective Boots", "type": "sprite"},
        {"id": 989, "name": "989 Night Vision Goggles", "type": "sprite"},
        {"id": 990, "name": "990 Armor", "type": "sprite"},
        {"id": 991, "mp": True, "name": "MP 991 Jetpack", "type": "sprite"},
        {"id": 992, "mp": True, "name": "MP 992 Atomic Health", "type": "sprite"},
        {"id": 993, "mp": True, "name": "MP 993 Atomic Health", "type": "sprite"},
        {"id": 994, "mp": True, "name": "MP 994 Steroids", "type": "sprite"},
        {"id": 995, "mp": True, "name": "MP 995 Jetpack", "type": "sprite"},
        {"id": 996, "mp": True, "name": "MP 996 Shrinker", "type": "sprite"},
        {"id": 997, "mp": True, "name": "MP 997 RPG", "type": "sprite"},
        {"id": 998, "mp": True, "name": "MP 998 Freezethrower", "type": "sprite"},
        {"id": 1007, "name": "1007 Tripmine", "type": "sprite"},
        {"id": 1008, "name": "1008 Shrinker", "type": "sprite"},
        {"id": 1009, "name": "1009 Tripmine", "type": "sprite"},
        {"id": 1016, "name": "1016 Atomic Health", "type": "sprite"},
        {"id": 1017, "name": "1017 Pipebombs", "type": "sprite"},
        {"id": 1018, "name": "1018 Pipebombs", "type": "sprite"},
        {"id": 1019, "name": "1019 Pipebombs", "type": "sprite"},
        {"id": 352, "name": "Secret 1", "type": "sector"},
        {"id": 579, "name": "Secret 2", "type": "sector"},
        {"id": 647, "name": "Secret 3", "type": "sector"},
        {"id": 675, "name": "Secret 4", "type": "sector"},
        {"id": 701, "name": "Secret 5", "type": "sector"},
        {"id": 713, "name": "Secret 6", "type": "sector"},
        {"id": 726, "name": "Secret 7", "type": "sector"},
        {"id": 0, "name": "Exit", "type": "exit"},
        {"id": 11, "name": "Secret Exit", "type": "exit"},
    ]
