from BaseClasses import Region

from ..base_classes import D3DLevel


class E4L10(D3DLevel):
    name = "The Queen"
    levelnum = 9
    volumenum = 3
    keys = ["Red"]
    location_defs = [
        {"id": 29, "name": "29 Jetpack", "type": "sprite"},
        {"id": 150, "name": "150 Protective Boots", "type": "sprite"},
        {"id": 151, "name": "151 Protective Boots", "type": "sprite"},
        {"id": 260, "name": "260 Atomic Health", "type": "sprite"},
        {"id": 297, "mp": True, "name": "MP 297 Shotgun", "type": "sprite"},
        {"id": 298, "mp": True, "name": "MP 298 Shotgun", "type": "sprite"},
        {"id": 299, "mp": True, "name": "MP 299 Shotgun", "type": "sprite"},
        {"id": 300, "mp": True, "name": "MP 300 Shotgun", "type": "sprite"},
        {"id": 312, "name": "312 Pipebombs", "type": "sprite"},
        {"id": 315, "name": "315 Pipebombs", "type": "sprite"},
        {"id": 316, "name": "316 Pipebombs", "type": "sprite"},
        {"id": 331, "name": "331 Medkit", "type": "sprite"},
        {"id": 332, "name": "332 Atomic Health", "type": "sprite"},
        {"id": 333, "name": "333 Armor", "type": "sprite"},
        {"id": 337, "name": "337 Scuba Gear", "type": "sprite"},
        {"id": 338, "name": "338 Protective Boots", "type": "sprite"},
        {"id": 374, "name": "374 Armor", "type": "sprite"},
        {"id": 375, "name": "375 Atomic Health", "type": "sprite"},
        {"id": 388, "mp": True, "name": "MP 388 Devastator", "type": "sprite"},
        {"id": 424, "name": "424 Medkit", "type": "sprite"},
        {"id": 453, "name": "453 RPG", "type": "sprite"},
        {"id": 561, "name": "561 Jetpack", "type": "sprite"},
        {"id": 579, "name": "579 RPG", "type": "sprite"},
        {"id": 613, "mp": True, "name": "MP 613 Shotgun", "type": "sprite"},
        {"id": 614, "mp": True, "name": "MP 614 Shotgun", "type": "sprite"},
        {"id": 615, "name": "615 Shotgun", "type": "sprite"},
        {"id": 616, "mp": True, "name": "MP 616 Shotgun", "type": "sprite"},
        {"id": 624, "name": "624 Jetpack", "type": "sprite"},
        {"id": 669, "mp": True, "name": "MP 669 Devastator", "type": "sprite"},
        {"id": 686, "name": "686 Pipebombs", "type": "sprite"},
        {"id": 701, "mp": True, "name": "MP 701 Shotgun", "type": "sprite"},
        {"id": 702, "mp": True, "name": "MP 702 Shotgun", "type": "sprite"},
        {"id": 776, "name": "776 Medkit", "type": "sprite"},
        {"id": 789, "name": "789 Blue Key Card", "type": "sprite"},
        {"id": 823, "name": "823 Red Key Card", "type": "sprite"},
        {"id": 824, "name": "824 Atomic Health", "type": "sprite"},
        {"id": 825, "name": "825 Armor", "type": "sprite"},
        {"id": 840, "name": "840 Armor", "type": "sprite"},
        {"id": 841, "name": "841 Armor", "type": "sprite"},
        {"id": 842, "name": "842 Yellow Key Card", "type": "sprite"},
        {"id": 844, "name": "844 Steroids", "type": "sprite"},
        {"id": 852, "name": "852 Atomic Health", "type": "sprite"},
        {"id": 859, "mp": True, "name": "MP 859 Chaingun", "type": "sprite"},
        {"id": 860, "mp": True, "name": "MP 860 Chaingun", "type": "sprite"},
        {"id": 861, "mp": True, "name": "MP 861 Chaingun", "type": "sprite"},
        {"id": 862, "mp": True, "name": "MP 862 Chaingun", "type": "sprite"},
        {"id": 891, "name": "891 Pipebombs", "type": "sprite"},
        {"id": 892, "name": "892 Pipebombs", "type": "sprite"},
        {"id": 893, "name": "893 Pipebombs", "type": "sprite"},
        {"id": 894, "mp": True, "name": "MP 894 Chaingun", "type": "sprite"},
        {"id": 895, "mp": True, "name": "MP 895 Chaingun", "type": "sprite"},
        {"id": 896, "name": "896 Chaingun", "type": "sprite"},
        {"id": 897, "name": "897 Chaingun", "type": "sprite"},
        {"id": 903, "name": "903 Devastator", "type": "sprite"},
        {"id": 904, "name": "904 Devastator", "type": "sprite"},
        {"id": 933, "name": "933 RPG", "type": "sprite"},
        {"id": 934, "name": "934 RPG", "type": "sprite"},
        {"id": 964, "name": "964 Pipebombs", "type": "sprite"},
        {"id": 65, "name": "Secret 1", "type": "sector"},
        {"id": 67, "name": "Secret 2", "type": "sector"},
        {"id": 70, "name": "Secret 3", "type": "sector"},
        {"id": 72, "name": "Secret 4", "type": "sector"},
        {"id": 197, "name": "Secret 5", "type": "sector"},
        {"id": 357, "name": "Secret 6", "type": "sector"},
        {"id": 630, "name": "Secret 7", "type": "sector"},
        {"id": 0, "name": "Exit", "type": "exit"},
    ]
