from BaseClasses import Region

from ..base_classes import D3DLevel


class E4L10(D3DLevel):
    name = "The Queen"
    levelnum = 9
    volumenum = 3
    keys = ["Red"]
    location_defs = [
        {"id": 29, "mp": True, "name": "MP 29 Jetpack", "type": "sprite"},
        {"id": 150, "mp": True, "name": "MP 150 Protective Boots", "type": "sprite"},
        {"id": 151, "mp": True, "name": "MP 151 Protective Boots", "type": "sprite"},
        {"id": 260, "mp": True, "name": "MP 260 Atomic Health", "type": "sprite"},
        {"id": 297, "name": "297 Shotgun", "type": "sprite"},
        {"id": 298, "name": "298 Shotgun", "type": "sprite"},
        {"id": 299, "name": "299 Shotgun", "type": "sprite"},
        {"id": 300, "name": "300 Shotgun", "type": "sprite"},
        {"id": 312, "mp": True, "name": "MP 312 Pipebombs", "type": "sprite"},
        {"id": 315, "mp": True, "name": "MP 315 Pipebombs", "type": "sprite"},
        {"id": 316, "mp": True, "name": "MP 316 Pipebombs", "type": "sprite"},
        {"id": 331, "mp": True, "name": "MP 331 Medkit", "type": "sprite"},
        {"id": 332, "mp": True, "name": "MP 332 Atomic Health", "type": "sprite"},
        {"id": 333, "mp": True, "name": "MP 333 Armor", "type": "sprite"},
        {"id": 337, "mp": True, "name": "MP 337 Scuba Gear", "type": "sprite"},
        {"id": 338, "mp": True, "name": "MP 338 Protective Boots", "type": "sprite"},
        {"id": 374, "mp": True, "name": "MP 374 Armor", "type": "sprite"},
        {"id": 375, "mp": True, "name": "MP 375 Atomic Health", "type": "sprite"},
        {"id": 388, "name": "388 Devastator", "type": "sprite"},
        {"id": 424, "mp": True, "name": "MP 424 Medkit", "type": "sprite"},
        {"id": 453, "mp": True, "name": "MP 453 RPG", "type": "sprite"},
        {"id": 561, "mp": True, "name": "MP 561 Jetpack", "type": "sprite"},
        {"id": 579, "mp": True, "name": "MP 579 RPG", "type": "sprite"},
        {"id": 613, "name": "613 Shotgun", "type": "sprite"},
        {"id": 614, "name": "614 Shotgun", "type": "sprite"},
        {"id": 615, "mp": True, "name": "MP 615 Shotgun", "type": "sprite"},
        {"id": 616, "name": "616 Shotgun", "type": "sprite"},
        {"id": 624, "mp": True, "name": "MP 624 Jetpack", "type": "sprite"},
        {"id": 669, "name": "669 Devastator", "type": "sprite"},
        {"id": 686, "mp": True, "name": "MP 686 Pipebombs", "type": "sprite"},
        {"id": 701, "name": "701 Shotgun", "type": "sprite"},
        {"id": 702, "name": "702 Shotgun", "type": "sprite"},
        {"id": 776, "mp": True, "name": "MP 776 Medkit", "type": "sprite"},
        {"id": 789, "mp": True, "name": "MP 789 Blue Key Card", "type": "sprite"},
        {"id": 823, "name": "823 Red Key Card", "type": "sprite"},
        {"id": 824, "mp": True, "name": "MP 824 Atomic Health", "type": "sprite"},
        {"id": 825, "mp": True, "name": "MP 825 Armor", "type": "sprite"},
        {"id": 840, "mp": True, "name": "MP 840 Armor", "type": "sprite"},
        {"id": 841, "mp": True, "name": "MP 841 Armor", "type": "sprite"},
        {"id": 842, "name": "842 Yellow Key Card", "type": "sprite"},
        {"id": 844, "mp": True, "name": "MP 844 Steroids", "type": "sprite"},
        {"id": 852, "mp": True, "name": "MP 852 Atomic Health", "type": "sprite"},
        {"id": 859, "name": "859 Chaingun", "type": "sprite"},
        {"id": 860, "name": "860 Chaingun", "type": "sprite"},
        {"id": 861, "name": "861 Chaingun", "type": "sprite"},
        {"id": 862, "name": "862 Chaingun", "type": "sprite"},
        {"id": 891, "mp": True, "name": "MP 891 Pipebombs", "type": "sprite"},
        {"id": 892, "mp": True, "name": "MP 892 Pipebombs", "type": "sprite"},
        {"id": 893, "mp": True, "name": "MP 893 Pipebombs", "type": "sprite"},
        {"id": 894, "name": "894 Chaingun", "type": "sprite"},
        {"id": 895, "name": "895 Chaingun", "type": "sprite"},
        {"id": 896, "mp": True, "name": "MP 896 Chaingun", "type": "sprite"},
        {"id": 897, "mp": True, "name": "MP 897 Chaingun", "type": "sprite"},
        {"id": 903, "mp": True, "name": "MP 903 Devastator", "type": "sprite"},
        {"id": 904, "mp": True, "name": "MP 904 Devastator", "type": "sprite"},
        {"id": 933, "mp": True, "name": "MP 933 RPG", "type": "sprite"},
        {"id": 934, "mp": True, "name": "MP 934 RPG", "type": "sprite"},
        {"id": 964, "mp": True, "name": "MP 964 Pipebombs", "type": "sprite"},
        {"id": 65, "name": "Secret 1", "type": "sector"},
        {"id": 67, "name": "Secret 2", "type": "sector"},
        {"id": 70, "name": "Secret 3", "type": "sector"},
        {"id": 72, "name": "Secret 4", "type": "sector"},
        {"id": 197, "name": "Secret 5", "type": "sector"},
        {"id": 357, "name": "Secret 6", "type": "sector"},
        {"id": 630, "name": "Secret 7", "type": "sector"},
        {"id": 0, "name": "Exit", "type": "exit"},
    ]
