from BaseClasses import Region

from ..base_classes import D3DLevel


class E4L9(D3DLevel):
    name = "Derelict"
    levelnum = 8
    volumenum = 3
    keys = ["Red"]
    location_defs = [
        {"id": 10, "name": "10 Medkit", "type": "sprite"},
        {"id": 65, "name": "65 Atomic Health", "type": "sprite"},
        {"id": 185, "name": "185 Atomic Health", "type": "sprite"},
        {"id": 211, "name": "211 Shrinker", "type": "sprite"},
        {"id": 214, "name": "214 Atomic Health", "type": "sprite"},
        {"id": 215, "name": "215 Atomic Health", "type": "sprite"},
        {"id": 216, "name": "216 Night Vision Goggles", "type": "sprite"},
        {"id": 217, "name": "217 Armor", "type": "sprite"},
        {"id": 223, "name": "223 Steroids", "type": "sprite"},
        {"id": 229, "name": "229 Chaingun", "type": "sprite"},
        {"id": 261, "name": "261 Pipebombs", "type": "sprite"},
        {"id": 504, "name": "504 Blue Key Card", "type": "sprite"},
        {"id": 626, "name": "626 Pipebombs", "type": "sprite"},
        {"id": 834, "name": "834 Protective Boots", "type": "sprite"},
        {"id": 960, "name": "960 Steroids", "type": "sprite"},
        {"id": 961, "name": "961 Medkit", "type": "sprite"},
        {"id": 962, "name": "962 RPG", "type": "sprite"},
        {"id": 964, "name": "964 RPG", "type": "sprite"},
        {"id": 967, "name": "967 Atomic Health", "type": "sprite"},
        {"id": 968, "name": "968 Atomic Health", "type": "sprite"},
        {"id": 969, "name": "969 Scuba Gear", "type": "sprite"},
        {"id": 970, "mp": True, "name": "MP 970 Jetpack", "type": "sprite"},
        {"id": 971, "mp": True, "name": "MP 971 Jetpack", "type": "sprite"},
        {"id": 972, "mp": True, "name": "MP 972 Jetpack", "type": "sprite"},
        {"id": 973, "name": "973 Armor", "type": "sprite"},
        {"id": 976, "name": "976 Shotgun", "type": "sprite"},
        {"id": 977, "name": "977 Chaingun", "type": "sprite"},
        {"id": 980, "name": "980 Shrinker", "type": "sprite"},
        {"id": 983, "name": "983 Tripbomb", "type": "sprite"},
        {"id": 984, "name": "984 Tripbomb", "type": "sprite"},
        {"id": 988, "name": "988 Freezethrower", "type": "sprite"},
        {"id": 989, "name": "989 Devastator", "type": "sprite"},
        {"id": 992, "name": "992 Night Vision Goggles", "type": "sprite"},
        {"id": 994, "name": "994 RPG", "type": "sprite"},
        {"id": 995, "mp": True, "name": "MP 995 Jetpack", "type": "sprite"},
        {"id": 996, "name": "996 Atomic Health", "type": "sprite"},
        {"id": 997, "name": "997 Holo Duke", "type": "sprite"},
        {"id": 1007, "name": "1007 Pipebombs", "type": "sprite"},
        {"id": 1008, "name": "1008 Pipebombs", "type": "sprite"},
        {"id": 1009, "name": "1009 Armor", "type": "sprite"},
        {"id": 1010, "name": "1010 Atomic Health", "type": "sprite"},
        {"id": 1011, "name": "1011 Chaingun", "type": "sprite"},
        {"id": 1012, "name": "1012 Shotgun", "type": "sprite"},
        {"id": 1021, "name": "1021 Red Key Card", "type": "sprite"},
        {"id": 1022, "name": "1022 Yellow Key Card", "type": "sprite"},
        {"id": 1058, "name": "1058 Atomic Health", "type": "sprite"},
        {"id": 1081, "name": "1081 Protective Boots", "type": "sprite"},
        {"id": 1082, "name": "1082 Steroids", "type": "sprite"},
        {"id": 1111, "name": "1111 Atomic Health", "type": "sprite"},
        {"id": 1118, "name": "1118 Atomic Health", "type": "sprite"},
        {"id": 1173, "mp": True, "name": "MP 1173 Jetpack", "type": "sprite"},
        {"id": 1181, "name": "1181 Chaingun", "type": "sprite"},
        {"id": 1182, "name": "1182 Steroids", "type": "sprite"},
        {"id": 1183, "name": "1183 Night Vision Goggles", "type": "sprite"},
        {"id": 1184, "name": "1184 Armor", "type": "sprite"},
        {"id": 1185, "name": "1185 Shotgun", "type": "sprite"},
        {"id": 347, "name": "Secret 1", "type": "sector"},
        {"id": 718, "name": "Secret 2", "type": "sector"},
        {"id": 761, "name": "Secret 3", "type": "sector"},
        {"id": 795, "name": "Secret 4", "type": "sector"},
        {"id": 800, "name": "Secret 5", "type": "sector"},
        {"id": 0, "name": "Exit", "type": "exit"},
    ]
