from BaseClasses import Region

from ..base_classes import D3DLevel


class E4L9(D3DLevel):
    name = "Derelict"
    levelnum = 8
    volumenum = 3
    keys = ["Red"]
    location_defs = [
        {"id": 10, "mp": True, "name": "MP 10 Medkit", "type": "sprite"},
        {"id": 65, "mp": True, "name": "MP 65 Atomic Health", "type": "sprite"},
        {"id": 185, "mp": True, "name": "MP 185 Atomic Health", "type": "sprite"},
        {"id": 211, "mp": True, "name": "MP 211 Shrinker", "type": "sprite"},
        {"id": 214, "mp": True, "name": "MP 214 Atomic Health", "type": "sprite"},
        {"id": 215, "mp": True, "name": "MP 215 Atomic Health", "type": "sprite"},
        {
            "id": 216,
            "mp": True,
            "name": "MP 216 Night Vision Goggles",
            "type": "sprite",
        },
        {"id": 217, "mp": True, "name": "MP 217 Armor", "type": "sprite"},
        {"id": 223, "mp": True, "name": "MP 223 Steroids", "type": "sprite"},
        {"id": 229, "mp": True, "name": "MP 229 Chaingun", "type": "sprite"},
        {"id": 261, "mp": True, "name": "MP 261 Pipebombs", "type": "sprite"},
        {"id": 504, "mp": True, "name": "MP 504 Blue Key Card", "type": "sprite"},
        {"id": 626, "mp": True, "name": "MP 626 Pipebombs", "type": "sprite"},
        {"id": 834, "mp": True, "name": "MP 834 Protective Boots", "type": "sprite"},
        {"id": 960, "mp": True, "name": "MP 960 Steroids", "type": "sprite"},
        {"id": 961, "mp": True, "name": "MP 961 Medkit", "type": "sprite"},
        {"id": 962, "mp": True, "name": "MP 962 RPG", "type": "sprite"},
        {"id": 964, "mp": True, "name": "MP 964 RPG", "type": "sprite"},
        {"id": 967, "mp": True, "name": "MP 967 Atomic Health", "type": "sprite"},
        {"id": 968, "mp": True, "name": "MP 968 Atomic Health", "type": "sprite"},
        {"id": 969, "mp": True, "name": "MP 969 Scuba Gear", "type": "sprite"},
        {"id": 970, "name": "970 Jetpack", "type": "sprite"},
        {"id": 971, "name": "971 Jetpack", "type": "sprite"},
        {"id": 972, "name": "972 Jetpack", "type": "sprite"},
        {"id": 973, "mp": True, "name": "MP 973 Armor", "type": "sprite"},
        {"id": 976, "mp": True, "name": "MP 976 Shotgun", "type": "sprite"},
        {"id": 977, "mp": True, "name": "MP 977 Chaingun", "type": "sprite"},
        {"id": 980, "mp": True, "name": "MP 980 Shrinker", "type": "sprite"},
        {"id": 983, "mp": True, "name": "MP 983 Tripbomb", "type": "sprite"},
        {"id": 984, "mp": True, "name": "MP 984 Tripbomb", "type": "sprite"},
        {"id": 988, "mp": True, "name": "MP 988 Freezethrower", "type": "sprite"},
        {"id": 989, "mp": True, "name": "MP 989 Devastator", "type": "sprite"},
        {
            "id": 992,
            "mp": True,
            "name": "MP 992 Night Vision Goggles",
            "type": "sprite",
        },
        {"id": 994, "mp": True, "name": "MP 994 RPG", "type": "sprite"},
        {"id": 995, "name": "995 Jetpack", "type": "sprite"},
        {"id": 996, "mp": True, "name": "MP 996 Atomic Health", "type": "sprite"},
        {"id": 997, "mp": True, "name": "MP 997 Holo Duke", "type": "sprite"},
        {"id": 1007, "mp": True, "name": "MP 1007 Pipebombs", "type": "sprite"},
        {"id": 1008, "mp": True, "name": "MP 1008 Pipebombs", "type": "sprite"},
        {"id": 1009, "mp": True, "name": "MP 1009 Armor", "type": "sprite"},
        {"id": 1010, "mp": True, "name": "MP 1010 Atomic Health", "type": "sprite"},
        {"id": 1011, "mp": True, "name": "MP 1011 Chaingun", "type": "sprite"},
        {"id": 1012, "mp": True, "name": "MP 1012 Shotgun", "type": "sprite"},
        {"id": 1021, "name": "1021 Red Key Card", "type": "sprite"},
        {"id": 1022, "name": "1022 Yellow Key Card", "type": "sprite"},
        {"id": 1058, "mp": True, "name": "MP 1058 Atomic Health", "type": "sprite"},
        {"id": 1081, "mp": True, "name": "MP 1081 Protective Boots", "type": "sprite"},
        {"id": 1082, "mp": True, "name": "MP 1082 Steroids", "type": "sprite"},
        {"id": 1111, "mp": True, "name": "MP 1111 Atomic Health", "type": "sprite"},
        {"id": 1118, "mp": True, "name": "MP 1118 Atomic Health", "type": "sprite"},
        {"id": 1173, "name": "1173 Jetpack", "type": "sprite"},
        {"id": 1181, "mp": True, "name": "MP 1181 Chaingun", "type": "sprite"},
        {"id": 1182, "mp": True, "name": "MP 1182 Steroids", "type": "sprite"},
        {
            "id": 1183,
            "mp": True,
            "name": "MP 1183 Night Vision Goggles",
            "type": "sprite",
        },
        {"id": 1184, "mp": True, "name": "MP 1184 Armor", "type": "sprite"},
        {"id": 1185, "mp": True, "name": "MP 1185 Shotgun", "type": "sprite"},
        {"id": 347, "name": "Secret 1", "type": "sector"},
        {"id": 718, "name": "Secret 2", "type": "sector"},
        {"id": 761, "name": "Secret 3", "type": "sector"},
        {"id": 795, "name": "Secret 4", "type": "sector"},
        {"id": 800, "name": "Secret 5", "type": "sector"},
        {"id": 0, "name": "Exit", "type": "exit"},
    ]
